#ifndef _IL2_DATA_H
#define _IL2_DATA_H

struct _IL2DATA_LIST
{
	LPTSTR		VarTokenName;
	UINT		VarID;
	int			VarType;
	BOOL		Writable;
	LPTSTR		Param;
	LPTSTR		Units;
	LPTSTR		Description;
};

struct _IL2CMD_LIST
{
	LPTSTR		VarTokenName;
	UINT		VarID;
	UINT		VarType;
	LPTSTR		Param;
	LPTSTR		Description;
};

_IL2DATA_LIST const IL2DataArray[] = { 
	{"",													0,		xplmType_Int,		0,		"",		"",			""},
	{"IL2/common/Version",									2,		xplmType_Char,		0,		"",		"string",	"containing DeviceLink version id."},
	{"IL2/common/time_of_day",								20,		xplmType_Float,		0,		"",		"hours",	"current tome of the day within the game."},
	{"IL2/common/plane",									22,		xplmType_Char,		0,		"",		"string",	"identifying the player plane."},
	{"IL2/common/cockpits",									24,		xplmType_Int,		0,		"",		"int",		"quantity of cockpits in the player aircraft."},
	{"IL2/common/cockpit_cur",								26,		xplmType_Int,		0,		"",		"int",		"number of the cockpit the player is currently in, starting with 0. The cockpit # 0 is always the pilot in command's cockpit. Returns -1 if the camera is on an external view."},
	{"IL2/common/engines",									28,		xplmType_Int,		0,		"",		"int",		"quantity of engines on the player aircraft."},
	{"IL2/instruments/speedometer_indicated",				30,		xplmType_Float,		0,		"",		"km/h",		"+0.00 +inf"},
	{"IL2/instruments/variometer",							32,		xplmType_Float,		0,		"",		"m/s",		"-inf +inf"},
	{"IL2/instruments/slip",								34,		xplmType_Float,		0,		"",		"deg",		"-45.00 +45.00"},
	{"IL2/instruments/turn",								36,		xplmType_Float,		0,		"",		"-1.00 +1.00", "turn indicator"},
	{"IL2/instruments/angular_speed",						38,		xplmType_Float,		0,		"",		"deg/s",	"-inf +inf"},
	{"IL2/instruments/altimeter",							40,		xplmType_Float,		0,		"",		"m",		"+0.00 +inf"},
	{"IL2/instruments/azimuth",								42,		xplmType_Float,		0,		"",		"deg",		"+0.00 +359.9"},
	{"IL2/instruments/beacon_azimuth",						44,		xplmType_Float,		0,		"",		"deg",		"+0.00 +359.9"},
	{"IL2/instruments/roll",								46,		xplmType_Float,		0,		"",		"deg",		"-180.00 +180.00"},
	{"IL2/instruments/pitch",								48,		xplmType_Float,		0,		"",		"deg",		"-90.00 +90.00"},
	{"IL2/instruments/fuel",								50,		xplmType_Float,		0,		"",		"kg",		"+0.00 +inf"},
	{"IL2/instruments/overload",							52,		xplmType_Float,		0,		"",		"-inf +inf",	"-inf +inf"},
	{"IL2/instruments/shake_level",							54,		xplmType_Float,		0,		"",		"+0.00 +1.00",	"+0.00 +1.00"},
	{"IL2/instruments/gear_pos_l",							56,		xplmType_Float,		0,		"",		"+0.00 +1.00",	"+0.00 +1.00 left gear leg position"},
	{"IL2/instruments/gear_pos_r",							58,		xplmType_Float,		0,		"",		"+0.00 +1.00",	"+0.00 +1.00 right gear leg position"},
	{"IL2/instruments/gear_pos_c",							60,		xplmType_Float,		0,		"",		"+0.00 +1.00",	"+0.00 +1.00 central gear position"},
	{"IL2/instruments/magneto_eng_1",						62,		xplmType_Int,		0,		"0",	"+0 +3",	"+0 +3"},
	{"IL2/instruments/magneto_eng_2",						62,		xplmType_Int,		0,		"1",	"+0 +3",	"+0 +3"},
	{"IL2/instruments/magneto_eng_3",						62,		xplmType_Int,		0,		"2",	"+0 +3",	"+0 +3"},
	{"IL2/instruments/magneto_eng_4",						62,		xplmType_Int,		0,		"3",	"+0 +3",	"+0 +3"},
	{"IL2/instruments/rpm_eng_1",							64,		xplmType_Float,		0,		"0",	"rpm",		"+0.00 +inf"},
	{"IL2/instruments/rpm_eng_2",							64,		xplmType_Float,		0,		"1",	"rpm",		"+0.00 +inf"},
	{"IL2/instruments/rpm_eng_3",							64,		xplmType_Float,		0,		"2",	"rpm",		"+0.00 +inf"},
	{"IL2/instruments/rpm_eng_4",							64,		xplmType_Float,		0,		"3",	"rpm",		"+0.00 +inf"},
	{"IL2/instruments/manifold_eng_1",						66,		xplmType_Float,		0,		"0",	"bar",		"+0.00 +inf"},
	{"IL2/instruments/manifold_eng_2",						66,		xplmType_Float,		0,		"1",	"bar",		"+0.00 +inf"},
	{"IL2/instruments/manifold_eng_3",						66,		xplmType_Float,		0,		"2",	"bar",		"+0.00 +inf"},
	{"IL2/instruments/manifold_eng_4",						66,		xplmType_Float,		0,		"3",	"bar",		"+0.00 +inf"},
	{"IL2/instruments/temp_oilin_eng_1",					68,		xplmType_Float,		0,		"0",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilin_eng_2",					68,		xplmType_Float,		0,		"1",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilin_eng_3",					68,		xplmType_Float,		0,		"2",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilin_eng_4",					68,		xplmType_Float,		0,		"3",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilout_eng_1",					70,		xplmType_Float,		0,		"0",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilout_eng_2",					70,		xplmType_Float,		0,		"1",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilout_eng_3",					70,		xplmType_Float,		0,		"2",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_oilout_eng_4",					70,		xplmType_Float,		0,		"3",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_water_eng_1",					72,		xplmType_Float,		0,		"0",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_water_eng_2",					72,		xplmType_Float,		0,		"1",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_water_eng_3",					72,		xplmType_Float,		0,		"2",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_water_eng_4",					72,		xplmType_Float,		0,		"3",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_cylinders_eng_1",				74,		xplmType_Float,		0,		"0",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_cylinders_eng_2",				74,		xplmType_Float,		0,		"1",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_cylinders_eng_3",				74,		xplmType_Float,		0,		"2",	"deg C",	"-273.00 +inf"},
	{"IL2/instruments/temp_cylinders_eng_4",				74,		xplmType_Float,		0,		"3",	"deg C",	"-273.00 +inf"},
	{"IL2/controls/Analog_Controls/get_Power",				80,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Power",				81,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Flaps",				82,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Flaps",				83,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Aileron",			84,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Aileron",			85,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Elevator",			86,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Elevator",			87,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Rudder",				88,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Rudder",				89,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Brakes",				90,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Brakes",				91,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Prop_Pitch",			92,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Prop Pitch",			93,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Aileron_Trim",		94,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Aileron Trim",		95,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Elevator_Trim",		96,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Elevator Trim",		97,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/get_Rudder_Trim",		98,		xplmType_Float,		0,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/Analog_Controls/set_Rudder Trim",		99,		xplmType_Float,		1,		"",		"-1.00 +1.00",	"-1.00 +1.00"},
	{"IL2/controls/discontinuous/Level_Stabilizer",			100,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Boost_On_Off",				104,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Magneto_Next",				106,	xplmType_Int,		0,		"",		"1 or 3",	"1 or 3"},
	{"IL2/controls/discontinuous/Magneto_Prev",				108,	xplmType_Int,		0,		"",		"1 or 3",	"1 or 3"},
	{"IL2/controls/discontinuous/Supercharger_Next_Stage",	110,	xplmType_Int,		0,		"",		"",			""},
	{"IL2/controls/discontinuous/Supercharger_Prev_Stage",	112,	xplmType_Int,		0,		"",		"",			""},
	{"IL2/controls/discontinuous/Feather_Prop",				162,	xplmType_Int,		0,		"",		"",			""},
	{"IL2/controls/discontinuous/Gear_Up_Down",				164,	xplmType_Float,		0,		"",		"",			""},
	{"IL2/controls/discontinuous/Airbrake",					172,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Lock_Tail_Wheel",			174,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Weapon_1",					180,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Weapon_2",					182,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Weapon_3",					184,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Weapon_4",					186,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Weapon_1_2",				188,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Toggle_Gun_Pods_On_Off",	190,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Toggle_Wing_Fold",			210,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Open_Close_Canopy",		212,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Toggle_Arresting_Hook",	214,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Toggle_Chocks",			216,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/controls/discontinuous/Gunner_Fire",				220,	xplmType_Int,		0,		"",		"1 or 0",	"1 or 0"},
	{"IL2/camera_control/Pilot_Gunner_Position",			300,	xplmType_Int,		0,		"",		"",			"current player cockpit idx"},
	{"IL2/camera_control/Toggle_FOV",						348,	xplmType_Float,		0,		"",		"deg",		"current FOV, degrees."}
};

//	COMMAND TYPE DATA
_IL2CMD_LIST const IL2CmdArray[] = {
	{"",													0,		xplmType_Cmd,	"",		""},
	{"IL2/controls/Level_Stabilizer",						101,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Engine",							103,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Boost_On_Off",							105,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Magneto_Next",							107,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Magneto_Prev",							109,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Supercharger_Next_Stage",				111,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Supercharger_Prev_Stage",				113,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_All_Engines",						115,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Unselect_All_Engines",					117,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Left_Engines",					119,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Right_Engines",					121,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_1",						123,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_2",						125,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_3",						127,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_4",						129,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_5",						131,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_6",						133,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_7",						135,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Engine_8",						137,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Selection_for_All_Engines",		139,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Left_Engines",					141,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Right_Engines",					143,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_1",				145,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_2",				147,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_3",				149,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_4",				151,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_5",				153,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_6",				155,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_7",				157,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Select_Unselect_Engine_8",				159,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Fire_Extinguisher",						161,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Feather_Prop",							163,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Gear_Up_Down",							165,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Rise_Gear_manually",						167,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Lower_Gear_manually",					169,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Cowl_or_Armor_Flaps",					171,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Airbrake",								173,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Lock_Tail_Wheel",						175,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Jettison_Droptanks",						177,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Attach_Detach_Aircraft",					179,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Weapon_1_start",							181,	xplmType_Cmd,	"1",	"start"},
	{"IL2/controls/Weapon_1_stop",							181,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/controls/Weapon_2_start",							183,	xplmType_Cmd,	"1",	"start"},
	{"IL2/controls/Weapon_2_stop",							183,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/controls/Weapon_3_start",							185,	xplmType_Cmd,	"1",	"start"},
	{"IL2/controls/Weapon_3_stop",							185,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/controls/Weapon_4_start",							187,	xplmType_Cmd,	"1",	"start"},
	{"IL2/controls/Weapon_4_stop",							187,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/controls/Weapon_1&2_start",						189,	xplmType_Cmd,	"1",	"start"},
	{"IL2/controls/Weapon_1&2_stop",						189,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/controls/Toggle_Gun_Pods_On_Off",					191,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Sight_Mode_Auto",					193,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Increase_Sight_Distance",				195,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Decrease_Sight_Distance",				197,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Adjust_Sight_Control_to_Right",			199,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Adjust_Sight_Control_to_Left",			201,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Increase_Sight_Altitude",				203,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Decrease_Sight_Altitude",				205,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Increase_Sight_Velocity",				207,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Decrease_Sight_Velocity",				209,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Wing_Fold",						211,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Open_Close_Canopy",						213,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Arresting_Hook",					215,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Toggle_Chocks",							217,	xplmType_Cmd,	"",		""},
	{"IL2/controls/Gunner_Fire_start",						221,	xplmType_Cmd,	"1",	"start"},
	{"IL2/controls/Gunner_Fire_stop",						221,	xplmType_Cmd,	"0",	"stop"},
//	{"IL2/controls/Gunner_Move",							223  set(int,int,int) Increment of mouse movement along the 3 axis. The third one is not used currently.
	{"IL2/camera_control/Pilot_Gunner_Position",			301,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_1",				303,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_2",				305,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_3",				307,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_4",				309,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_5",				311,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_6",				313,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_7",				315,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_8",				317,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_9",				319,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Jump_to_Cockpit_10",				321,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_90",							323,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_85",							325,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_80",							327,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_75",							329,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_70",							331,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_65",							333,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_60",							335,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_55",							337,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_50",							339,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_45",							341,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_40",							343,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_35",							345,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/FOV_30",							347,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Toggle_FOV",						349,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Increase_FOV",						351,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Decrease_FOV",						353,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Cockpit_View",						355,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/No_Cockpit_View",					357,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/External_View",					359,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Next_Friendly_View",				361,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Next_Enemy_View",					363,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Fly_by_View",						365,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Padlock_Enemy",					367,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Padlock_Friendly",					369,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Padlock_Enemy_Ground",				371,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Padlock_Friendly_Ground",			373,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Padlock_Next",						375,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Padlock_Previous",					377,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Instant_View_Forward_with_Padlock_start",	479,	xplmType_Cmd,	"1",	"start"},
	{"IL2/camera_control/Instant_View_Forward_with_Padlock_stop",	479,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/camera_control/External_Padlock/Enemy_Air",		381,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/External_Padlock/Friendly_Air",	383,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/External_Padlock/closest_Enemy_Air",		385,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/External_Padlock/Enemy_Ground",	387,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/External_Padlock/Friendly_Ground",	389,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/External_Padlock/closest_Enemy_Ground",	391,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Chase_View",						393,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Next_Friendly_Chase_View",			395,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Next_Enemy_Chase_View",			397,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Toggle_Gunsight",					399,	xplmType_Cmd,	"",		""},
	{"IL2/camera_control/Toggle_Seat_Position",				447,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Autopilot",						401,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Level_Autopilot",				403,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Bail_Out",								405,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Tinted_Reticle_Dimmer_German_Planes",	407,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Cockpit_Lights",						409,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Nav_Lights",					411,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Landing_Light",					413,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Wingtip_Smoke",					415,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Map",							417,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Chat",									419,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Online_Rating_show",					421,	xplmType_Cmd,	"1",	"show"},
	{"IL2/parameters/Online_Rating_hide",					421,	xplmType_Cmd,	"0",	"hide"},
	{"IL2/parameters/Next_Ratings_Page",					443,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Speed_Bar",						423,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Icon_Types",					425,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Toggle_Mirrors_Show_Mode",				427,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Quick_Start_Save_Track",				429,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Radio_Mute_Key_start",					431,	xplmType_Cmd,	"1",	"start"},
	{"IL2/parameters/Radio_Mute_Key_stop",					431,	xplmType_Cmd,	"0",	"stop"},
	{"IL2/parameters/Mute",									445,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Radio_Channel_Switch",					433,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Accelerate_Time_x2_x4_x8",				435,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Normal_Time",							437,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Decelerate_Time_x2_x4",				439,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/PauseGame",							441,	xplmType_Cmd,	"",		""},
	{"IL2/parameters/Time_Skip",							449,	xplmType_Cmd,	"",		""}
};
#endif