//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by USIM.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_COLLAPSE                     102
#define ID_REFRESH                      103
#define ID_CLEAR                        104
#define ID_DISABLE_ITEM                 105
#define IDC_GROUP2                      105
#define ID_HIDE_ITEMS                   106
#define ID_SWAP                         107
#define ID_REMOVE                       108
#define ID_SETTINGS                     109
#define ID_NONE                         110
#define ID_INPUTS                       111
#define ID_DEVICE                       112
#define ID_VIRTUAL                      113
#define ID_EXPAND                       114
#define IDR_MAINFRAME                   115
#define ID_OUTPUTS                      116
#define ID_PORT                         117
#define ID_ROTARIES                     118
#define ID_CLCD                         119
#define ID_INPUT                        120
#define ID_FILE_LOAD                    121
#define ID_OUTPUT                       122
#define ID_ROTARY                       123
#define ID_LOCAL                        124
#define ID_MUX                          125
#define IDI_DIS_OFF_P                   126
#define IDD_USIM_DIALOG                 127
#define IDD_DATAOUT                     129
#define ID_MULTIPLEXED                  130
#define ID_DEFAULT                      131
#define IDI_F4OFF                       132
#define IDI_USIM_OFF                    132
#define ID_INDICATOR_1                  133
#define ID_SEG                          135
#define ID_RWR                          136
#define IDI_MINUS                       137
#define IDD_CALSPI                      138
#define ID_GLCD                         139
#define ID_NETWORK                      140
#define ID_DAC                          142
#define IDI_SIMS                        142
#define ID_HIDE_PORTS                   143
#define IDD_VARSLIST                    143
#define IDI_RESTORE                     144
#define ID_HIDE_MODES                   145
#define ID_DACS                         146
#define IDC_SPLITTER                    146
#define ID_CLEAR_ITEM                   147
#define IDI_FALCON                      148
#define IDR_MENU1                       149
#define IDI_INSTALL                     149
#define IDI_CARD2                       150
#define IDD_LCD_LINES                   150
#define IDI_USB                         151
#define IDI_JOY                         152
#define ID_INDICATOR_2                  153
#define IDD_DEFAULT                     154
#define IDI_NA                          155
#define IDI_QUE_YELLOW                  156
#define IDI_ON                          157
#define IDI_DOWN                        158
#define IDI_OFF                         159
#define IDI_CARD                        160
#define IDI_ON_RED                      161
#define IDI_PORT                        162
#define IDI_NETHOOD                     163
#define IDI_PC3                         164
#define IDI_DIG1                        165
#define IDI_AN1                         166
#define IDB_LOGO                        167
#define IDR_POPMENU                     168
#define IDC_CANCEL                      169
#define IDI_HELP                        170
#define IDI_WEB                         171
#define IDI_UPDATE                      172
#define IDI_PLCC                        173
#define IDI_JP                          174
#define ID_UVARS                        180
#define ID_SPI                          182
#define ID_LATCHED                      183
#define ID_DMXS                         185
#define ID_SPIS                         186
#define ID_LO                           187
#define ID_DMX                          188
#define IDC_OPTIONSTREE_OPTIONS         189
#define IDD_VARLIST                     190
#define ID_STEPS                        192
#define ID_STEP                         193
#define ID_COPY_ITEM                    194
#define ID_PASTE_ITEM                   195
#define ID_EXPORT_ITEM                  196
#define ID_IMPORT_ITEM                  197
#define IDC_GRID                        1000
#define IDC_EDIT1                       1001
#define IDC_R_GRID                      1001
#define IDC_CHECK1                      1002
#define IDC_LIST1                       1003
#define IDC_CHECK2                      1003
#define IDC_EDIT3                       1003
#define IDC_AUTOCONNECT                 1004
#define IDC_ED_SEARCH_ITEM              1004
#define IDC_EDIT4                       1004
#define IDC_AUTOLOAD                    1005
#define IDC_REPEAT                      1005
#define IDC_BT_SEARCH_ITEM              1005
#define IDC_DISABLE                     1005
#define IDC_EDIT5                       1005
#define IDC_AUTOMATCH                   1006
#define IDC_AUTOUPDATE                  1006
#define IDC_BT_RESET_SEARCH             1006
#define IDC_BUTTON1                     1007
#define IDC_MINIMIZED                   1008
#define IDC_BUTTON2                     1008
#define IDC_REMOVE                      1009
#define IDC_AUTOSTART                   1009
#define IDC_BUTTON3                     1009
#define IDC_ADD                         1010
#define IDC_BUTTON4                     1010
#define IDC_ENABLE_RWR                  1011
#define IDC_P_REMOVE                    1011
#define IDC_GROUP1                      1012
#define IDC_BUTTON5                     1012
#define IDC_VERSION                     1013
#define IDC_P_ADD                       1013
#define IDC_REFRESH                     1014
#define IDC_ENABLE_PFL                  1015
#define IDC_R_ADD                       1015
#define IDC_UPDATE                      1016
#define IDC_ENABLE_DED                  1017
#define IDC_R_REMOVE                    1017
#define IDC_HELP2                       1018
#define IDC_SLIDER1                     1019
#define IDC_P_CLEAR                     1019
#define IDC_WEB                         1020
#define IDC_SLIDER3                     1020
#define IDC_SLIDER2                     1021
#define IDC_R_CLEAR                     1021
#define IDC_RADIO1                      1022
#define IDC_FALCON                      1023
#define IDC_RADIO2                      1024
#define IDC_RADIO3                      1025
#define IDC_SIM_COMBO                   1026
#define IDC_OP_VALUE                    1027
#define IDC_OP_COMBO2                   1028
#define IDC_OP_COMBO3                   1029
#define IDC_OP_VALUE2                   1030
#define IDC_UV_COMBO                    1031
#define IDC_STATIC6                     1031
#define IDC_UVOP_VALUE                  1032
#define IDC_STATIC7                     1032
#define IDC_MIN                         1033
#define IDC_UVOP_COMBO2                 1033
#define IDC_STATIC10                    1033
#define IDC_UVOP_COMBO3                 1034
#define IDC_STATIC8                     1034
#define IDC_OFFSET                      1034
#define IDC_CALIBRATE_MIN               1035
#define IDC_UVOP_VALUE2                 1035
#define IDC_DEFAULTS                    1036
#define IDC_CALIBRATE_OFFSET            1036
#define IDC_STATIC0                     1037
#define IDC_HOLDKEY                     1038
#define IDC_STATIC3                     1038
#define IDC_CALIBRATE                   1039
#define IDC_P_GRID                      1039
#define IDC_STATIC4                     1039
#define IDC_ZERO                        1040
#define IDC_VAR_COMBO                   1040
#define IDC_CALIBRATE_MAX               1041
#define IDC_STATIC9                     1042
#define IDC_LIMIT                       1043
#define IDC_STATIC5                     1043
#define IDC_LAMPTEST                    1044
#define IDC_LB1_COMBO                   1045
#define IDC_STATIC1                     1046
#define IDC_OP_COMBO                    1047
#define IDC_STATIC13                    1047
#define IDC_STATIC2                     1048
#define IDC_UVOP_COMBO                  1048
#define IDC_INVERT                      1049
#define IDC_MINMAX                      1049
#define IDC_SMINMAX                     1049
#define IDC_EDIT2                       1050
#define IDC_STATIC11                    1050
#define IDC_HSI_COMBO                   1051
#define IDC_ACTIVATE                    1052
#define IDC_TREE                        1052
#define IDC_POWERFLAG                   1053
#define IDC_FLIGHTDATA                  1053
#define IDC_TEXT1                       1054
#define IDC_CLEARITEM                   1055
#define IDC_OP_FLIGHTDATA               1055
#define IDC_CLEARALL                    1056
#define IDC_OR_FLIGHTDATA               1057
#define IDC_MASKDATA                    1057
#define IDC_OR_TEXT                     1058
#define IDC_TEXT2                       1058
#define IDC_OP_TEXT                     1059
#define IDC_MAX_TEXT                    1060
#define IDC_CLEARDATA                   1060
#define IDC_OR_CLEARDATA                1060
#define IDC_OP_CLEARDATA                1061
#define IDC_VALUETEXT                   1061
#define IDC_CLEARMASK                   1061
#define IDC_COMBO_DISPLAY               1065
#define IDC_COMBO_PREV                  1066
#define IDC_COMBO_NEXT                  1067
#define IDC_STATIC12                    1070
#define IDC_SPIN1                       1074
#define IDC_SPIN2                       1075
#define IDC_EMINMAX                     1075
#define IDC_SPIN3                       1076
#define IDC_TAB1                        2000
#define IDC_DEVICESTREE                 2001
#define IDC_OUTPUTNAME                  2002
#define IDC_TAB2                        2003
#define IDC_TAB3                        2004
#define IDC_TAB4                        2005
#define IDD_REPLACE                     2006
#define IDC_TAB5                        2007
#define IDC_NOTES                       2008
#define IDC_TAB6                        2009
#define IDD_OUTPUTS                     2010
#define IDD_OUTPUT                      2010
#define IDC_TAB7                        2011
#define IDD_MUX                         2012
#define IDC_TAB8                        2013
#define IDC_OB_SLIDER                   2014
#define IDC_TAB9                        2014
#define IDD_7SEG                        2015
#define IDC_TAB10                       2015
#define IDI_CARD3                       2016
#define IDC_TAB11                       2016
#define IDD_RWR                         2017
#define IDC_TAB12                       2017
#define IDC_OB_CLEAR                    2018
#define IDD_GLCD                        2019
#define IDD_SPIDAC                      2020
#define IDC_OB_LEVEL_SLIDER             2021
#define IDD_DUAL_DAC                    2022
#define IDI_RED_ON                      2023
#define IDI_RED_OFF                     2024
#define IDI_GR_ON                       2025
#define IDI_GR_OFF                      2026
#define IDC_OB_TEXT1                    2027
#define IDI_KEYS                        2028
#define IDC_OB_TEXT2                    2029
#define IDC_OB_RATE                     2030
#define IDI_OUTPUT                      2031
#define IDC_OB_TEXT3                    2032
#define IDI_GR_OFF_P                    2033
#define IDC_OB_TEXT4                    2034
#define IDI_GR_ON_P                     2035
#define IDC_ENABLE                      2036
#define IDI_DIS_ON                      2037
#define IDC_OB_LEVEL                    2038
#define IDI_DIS_ON_P                    2039
#define IDC_ONPRESS                     2039
#define IDC_MAX                         2040
#define IDI_DIS_OFF                     2041
#define IDC_OK                          2042
#define IDC_ONRELEASE                   2042
#define IDI_INPUT                       2043
#define IDI_GEAR                        2044
#define IDI_ROTARY                      2045
#define IDI_LCD_DIS                     2046
#define IDI_CLCD_DIS                    2046
#define IDI_MUX                         2047
#define IDI_ALPHA                       2048
#define IDI_PLCC_DIS                    2049
#define IDC_CLEAR                       2049
#define IDI_INPUT_DIS                   2050
#define IDI_ROTARY_DIS                  2051
#define IDI_OUTPUT_DIS                  2052
#define IDI_USB1                        2053
#define IDC_PRESS_REC                   2053
#define IDI_RED_OFF_P                   2054
#define IDI_RED_ON_P                    2055
#define IDI_FALCON_ON                   2056
#define IDC_RELEASE_REC                 2056
#define IDI_MUX_DIS                     2057
#define IDI_F4ON                        2058
#define IDI_USIM_ON                     2058
#define IDI_F4ON1                       2059
#define IDI_USIM_ON1                    2059
#define IDI_JP_DIS                      2060
#define IDI_PLUS                        2061
#define IDI_MUX_P                       2062
#define IDI_MUX_DIS_P                   2063
#define IDI_RWR                         2064
#define IDC_DESC                        2064
#define IDI_RWR_DIS                     2065
#define IDI_RWR_P                       2066
#define IDI_RWR_DIS_P                   2067
#define IDI_GLCD                        2068
#define IDI_GLCD_DIS                    2069
#define IDC_OP_DEC                      2069
#define IDI_GLCD_DIS_P                  2070
#define IDC_OP_MASK                     2070
#define IDI_GLCD_P                      2071
#define IDC_OP_INC                      2071
#define IDI_DACS                        2072
#define IDC_OR_VALUE                    2072
#define IDI_DACS_DIS                    2073
#define IDC_MIN_VALUE                   2074
#define IDC_OR_MASK                     2074
#define IDI_DUALDAC                     2075
#define IDC_OR_DEC                      2075
#define IDI_DAC_DIS                     2076
#define IDC_OR_INC                      2076
#define IDC_MAX_VALUE                   2077
#define IDI_DUALDAC_DIS                 2078
#define IDI_DAC_P                       2079
#define IDI_DUALDAC_P                   2080
#define IDI_DAC_DIS_P                   2081
#define IDI_DUALDAC_DIS_P               2082
#define IDI_DAC1                        2083
#define IDI_DAC                         2084
#define IDI_KBS2_P                      2118
#define IDI_NOTES_P                     2123
#define IDD_NOTES                       2124
#define IDD_SEND_KEYS                   2125
#define IDD_USERVARS                    2126
#define IDD_INPUT_FLAGS                 2126
#define IDD_COND_INPUT                  2127
#define IDD_OUTPUT_FLAGS                2128
#define IDD_SIMPATH                     2129
#define IDI_COND                        2130
#define IDD_VARIABLES                   2130
#define IDI_COND_P                      2131
#define IDD_CALSTEP                     2131
#define IDI_VARS                        2132
#define IDI_VARS_P                      2133
#define IDI_VARS_B                      2134
#define IDI_NOTES_B                     2135
#define IDI_NOTES                       2136
#define IDI_OUTPUT_P                    2137
#define IDI_KBS                         2138
#define IDI_KBS_ON                      2139
#define IDC_IONAME                      2140
#define IDI_KBS1                        2140
#define IDI_KBS_OFF                     2141
#define IDC_OP_COMBO1                   2141
#define IDI_KBS2                        2142
#define IDI_COND_B                      2143
#define IDC_OP_RADIO2                   2143
#define IDI_SPI_P                       2144
#define IDC_OP_RADIO4                   2144
#define IDI_SPI_DIS_P                   2145
#define IDC_OP_RADIO3                   2145
#define IDI_SPI_DIS                     2146
#define IDC_OR_COMBO1                   2146
#define IDI_SPI                         2147
#define IDC_OR_RADIO1                   2147
#define IDC_OR_RADIO2                   2148
#define IDC_OR_RADIO4                   2149
#define IDC_OR_RADIO3                   2150
#define IDC_OP_RADIO1                   2151
#define IDI_SPIS                        2152
#define IDI_SPIS_DIS                    2153
#define IDC_OP_INC_SPIN                 2153
#define IDI_DMXS                        2154
#define IDC_OP_DEC_SPIN                 2154
#define IDI_DMX                         2155
#define IDC_OR_INC_SPIN                 2155
#define IDI_DMX_P                       2156
#define IDC_OR_DEC_SPIN                 2156
#define IDI_DMX_DIS                     2157
#define IDI_DMX_DIS_P                   2158
#define IDI_DMXS_DIS                    2159
#define IDI_LO                          2160
#define IDI_LO_DIS                      2161
#define IDI_LO_P                        2162
#define IDI_SPIS_P                      2163
#define IDI_DACS_P                      2164
#define IDI_DMXS_P                      2165
#define IDI_BROWSE                      2166
#define IDI_CLEAR                       2167
#define IDI_USIM_RED                    2168
#define IDI_USIM_ONGR                   2169
#define IDI_USIM_ONGR1                  2170
#define IDI_USIM_DIS                    2171
#define IDI_USIM_DIS_RED                2172
#define IDI_LCD_DIS_P                   2173
#define IDI_CLCD_DIS_P                  2173
#define IDI_LCD_P                       2175
#define IDI_CLCD_P                      2175
#define IDI_LCD                         2176
#define IDI_CLCD                        2176
#define IDI_LCD_PAGE                    2177
#define IDI_LCD_PAGE_P                  2178
#define IDI_LCD_PAGE_DIS                2179
#define IDI_LCD_PAGE_DIS_P              2180
#define IDI_SPIS_P1                     2181
#define IDI_STEPS_P                     2181
#define IDI_STEPS_DIS                   2182
#define IDI_STEPS                       2183
#define IDI_STEP_P                      2184
#define IDI_STEP_DIS_P                  2185
#define IDI_STEP_DIS                    2186
#define IDI_STEP                        2187
#define IDC_XBAR                        2211
#define ID_F4CONNECT                    32771
#define ID_TRAY_RESTORE                 32772
#define ID_SHOWDATA                     32773
#define IDS_UPDATE                      32774
#define ID_F4DISCONNECT                 32775
#define IDS_HELPFILE                    32775
#define IDS_FIRM_UPDATE                 32776
#define ID_F4AUTOCONNECT                32777
#define ID_AUTOCONNECT                  32777
#define ID_KBSCONNECT                   32780
#define ID_F4SHOWDATA                   32781
#define ID_DISABLE                      32782
#define IDS_UPDATE_AVAILABLE            61458
#define IDS_UPDATE_NO                   61459
#define IDS_UPDATE_NOCHECK              61460
#define IDS_VERSION                     61464

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           198
#endif
#endif
