#ifndef _RF_DATA_H
#define _RF_DATA_H

struct _RFDATA_LIST
{
	LPTSTR		VarTokenName;
	int			VarType;
	BOOL		Writable;
	LPTSTR		Units;
	LPTSTR		Description;
};

_RFDATA_LIST const RFDataArray[] = { 
	{"",													xplmType_Int,		0,		"",			""},
	{"rFactor/scoring_info/mCurrentET",						xplmType_Float,		0,		"",			"current time"},
	{"rFactor/scoring_info/mEndET",							xplmType_Float,		0,		"",			"ending time"},
	{"rFactor/scoring_info/mGamePhase",						xplmType_Int,		0,		"",			"Game phases: 0 Before session has begun, 1 Reconnaissance laps, 2 Grid walk-through, 3 Formation lap, 4 Starting-light countdown has begun, 5 Green flag, 6 Full course yellow / safety car, 7 Session stopped, 8 Session over"},
	{"rFactor/scoring_info/mLapDist",						xplmType_Float,		0,		"",			"distance around track"},
	{"rFactor/scoring_info/mMaxLaps",						xplmType_Int,		0,		"",			"maximum laps"},
	{"rFactor/scoring_info/mNumRedLights",					xplmType_Int,		0,		"",			"number of red lights in start sequence"},
	{"rFactor/scoring_info/mNumVehicles",					xplmType_Int,		0,		"",			"current number of vehicles"},
	{"rFactor/scoring_info/mSectorFlag_1",					xplmType_Int,		0,		"",			"whether there are any local yellows at the moment in each sector"},
	{"rFactor/scoring_info/mSectorFlag_2",					xplmType_Int,		0,		"",			"whether there are any local yellows at the moment in each sector"},
	{"rFactor/scoring_info/mSectorFlag_3",					xplmType_Int,		0,		"",			"whether there are any local yellows at the moment in each sector"},
	{"rFactor/scoring_info/mSession",						xplmType_Int,		0,		"",			"current session"},
	{"rFactor/scoring_info/mStartLight",					xplmType_Int,		0,		"",			" start light frame (number depends on track)"},
	{"rFactor/scoring_info/mTrackName",						xplmType_Char,		0,		"string",	"current track name"},
	{"rFactor/scoring_info/mYellowFlagState",				xplmType_Int,		0,		"",			"Yellow flag states: -1 Invalid, 0 None, 1 Pending, 2 Pits closed, 3 Pit lead lap, 4 Pits open, 5 Last lap, 6 Resume, 7 Race halt (not currently used)"},
	{"rFactor/scoring_info/weather/mAmbientTemp",			xplmType_Float,		0,		"deg C",	"temperature"},
	{"rFactor/scoring_info/weather/mDarkCloud",				xplmType_Float,		0,		"",			"cloud darkness? 0.0-1.0"},
	{"rFactor/scoring_info/weather/mRaining",				xplmType_Float,		0,		"",			"raining severity 0.0-1.0"},
	{"rFactor/scoring_info/weather/mTrackTemp",				xplmType_Float,		0,		"deg C",	"temperature"},
	{"rFactor/telemetry/driver/mDeltaTime",					xplmType_Float,		0,		"sec",		"time since last update"},		
	{"rFactor/telemetry/driver/mLapNumber",					xplmType_Int,		0,		"",			"current lap number"},	
	{"rFactor/telemetry/driver/mLapStartET",				xplmType_Float,		0,		"sec",		"time this lap was started"},		
	{"rFactor/telemetry/driver/mScheduledStops",			xplmType_Int,		0,		"",			"number of scheduled pitstops"},		
	{"rFactor/telemetry/engine/mEngineMaxRPM",				xplmType_Float,		0,		"rpm",		"rev limit"},			
	{"rFactor/telemetry/engine/mEngineOilTemp",				xplmType_Float,		0,		"deg C",	"Oil Temp"},				
	{"rFactor/telemetry/engine/mEngineRPM",					xplmType_Float,		0,		"rpm",		"engine RPM"},		
	{"rFactor/telemetry/engine/mEngineWaterTemp",			xplmType_Float,		0,		"deg C",	"Water Temp"},				
	{"rFactor/telemetry/engine/mOverheating",				xplmType_Int,		0,		"bool",		"whether overheating icon is shown"},		
	{"rFactor/telemetry/vehicle/mClutchRPM",				xplmType_Float,		0,		"rpm",		"clutch RPM"},		
	{"rFactor/telemetry/vehicle/mDetached",					xplmType_Int,		0,		"bool",		"whether any parts (besides wheels) have been detached"},		
	{"rFactor/telemetry/vehicle/mFuel",						xplmType_Float,		0,		"liters",	"amount of fuel"},		
	{"rFactor/telemetry/vehicle/mGear",						xplmType_Int,		0,		"",			"-1=reverse, 0=neutral, 1+=forward gears"},
	{"rFactor/telemetry/vehicle/mLastImpactET",				xplmType_Float,		0,		"",			"time of last impact"},
	{"rFactor/telemetry/vehicle/mLocalAccelX",				xplmType_Float,		0,		"m/ss",		"acceleration (meters/sec^2) in local vehicle coordinates"},
	{"rFactor/telemetry/vehicle/mLocalAccelY",				xplmType_Float,		0,		"m/ss",		"acceleration (meters/sec^2) in local vehicle coordinates"},
	{"rFactor/telemetry/vehicle/mLocalAccelZ",				xplmType_Float,		0,		"m/ss",		"acceleration (meters/sec^2) in local vehicle coordinates"},
	{"rFactor/telemetry/vehicle/mLocalVelX",				xplmType_Float,		0,		"m/s",		"velocity (meters/sec) in local vehicle coordinates"},
	{"rFactor/telemetry/vehicle/mLocalVelY",				xplmType_Float,		0,		"m/s",		"velocity (meters/sec) in local vehicle coordinates"},
	{"rFactor/telemetry/vehicle/mLocalVelZ",				xplmType_Float,		0,		"m/s",		"velocity (meters/sec) in local vehicle coordinates"},
	{"rFactor/telemetry/vehicle/mSteeringArmForce",			xplmType_Float,		0,		"",			"force on steering arms"},
	{"rFactor/telemetry/vehicle/mUnfilteredThrottle",		xplmType_Float,		0,		"",			"ranges  0.0-1.0"},
	{"rFactor/telemetry/vehicle/mUnfilteredBrake",			xplmType_Float,		0,		"",			"ranges  0.0-1.0"},
	{"rFactor/telemetry/vehicle/mUnfilteredClutch",			xplmType_Float,		0,		"",			"ranges  0.0-1.0"},
	{"rFactor/telemetry/vehicle/wheels/FL_mBrakeTemp",		xplmType_Float,		0,		"deg C",	"Front Left brake temp"},						
	{"rFactor/telemetry/vehicle/wheels/FL_mPressure",		xplmType_Float,		0,		"kPa",		"Front Left pressure"},				
	{"rFactor/telemetry/vehicle/wheels/FL_Wheel_C_Temp",	xplmType_Float,		0,		"deg C",	"Front Left Wheel Center temp"},						
	{"rFactor/telemetry/vehicle/wheels/FL_Wheel_L_Temp",	xplmType_Float,		0,		"deg C",	"Front Left Wheel Left temp"},						
	{"rFactor/telemetry/vehicle/wheels/FL_Wheel_R_Temp",	xplmType_Float,		0,		"deg C",	"Front Left Wheel Right temp"},						
	{"rFactor/telemetry/vehicle/wheels/FR_mBrakeTemp",		xplmType_Float,		0,		"deg C",	"Front Right brake temp"},						
	{"rFactor/telemetry/vehicle/wheels/FR_mPressure",		xplmType_Float,		0,		"kPa",		"Front Right pressure"},				
	{"rFactor/telemetry/vehicle/wheels/FR_Wheel_C_Temp",	xplmType_Float,		0,		"deg C",	"Front Right Wheel Center temp"},						
	{"rFactor/telemetry/vehicle/wheels/FR_Wheel_L_Temp",	xplmType_Float,		0,		"deg C",	"Front Right Wheel Left temp"},						
	{"rFactor/telemetry/vehicle/wheels/FR_Wheel_R_Temp",	xplmType_Float,		0,		"deg C",	"Front Right Wheel Right temp"},						
	{"rFactor/telemetry/vehicle/wheels/RL_mBrakeTemp",		xplmType_Float,		0,		"deg C",	"Rear Left brake temp"},						
	{"rFactor/telemetry/vehicle/wheels/RL_mPressure",		xplmType_Float,		0,		"kPa",		"Rear Left pressure"},				
	{"rFactor/telemetry/vehicle/wheels/RL_Wheel_C_Temp",	xplmType_Float,		0,		"deg C",	"Rear Left Wheel Center temp"},						
	{"rFactor/telemetry/vehicle/wheels/RL_Wheel_L_Temp",	xplmType_Float,		0,		"deg C",	"Rear Left Wheel Left temp"},						
	{"rFactor/telemetry/vehicle/wheels/RL_Wheel_R_Temp",	xplmType_Float,		0,		"deg C",	"Rear Left Wheel Right temp"},						
	{"rFactor/telemetry/vehicle/wheels/RR_mBrakeTemp",		xplmType_Float,		0,		"deg C",	"Rear Right brake temp"},						
	{"rFactor/telemetry/vehicle/wheels/RR_mPressure",		xplmType_Float,		0,		"kPa",		"Rear Right pressure"},				
	{"rFactor/telemetry/vehicle/wheels/RR_Wheel_C_Temp",	xplmType_Float,		0,		"deg C",	"Rear Right Wheel Center temp"},						
	{"rFactor/telemetry/vehicle/wheels/RR_Wheel_L_Temp",	xplmType_Float,		0,		"deg C",	"Rear Right Wheel Left temp"},						
	{"rFactor/telemetry/vehicle/wheels/RR_Wheel_R_Temp",	xplmType_Float,		0,		"deg C",	"Rear Right Wheel Right temp"},						
	{"rFactor/telemetry/world/mTrackName",					xplmType_Char,		0,		"string",	"current track name"},			
	{"rFactor/telemetry/world/mVehicleName",				xplmType_Char,		0,		"string",	"current vehicle name"},
	{"rFactor/vehicle_score/dash_indicators/mLapsBehindLeader",		xplmType_Int,		0,		"",		"laps behind leader"},
	{"rFactor/vehicle_score/dash_indicators/mLapsBehindNext",		xplmType_Int,		0,		"",		"laps behind vehicle in next higher place"},
	{"rFactor/vehicle_score/dash_indicators/mLapStartET",			xplmType_Float,		0,		"",		"time this lap was started"},
	{"rFactor/vehicle_score/dash_indicators/mTimeBehindLeader",		xplmType_Float,		0,		"",		"time behind leader"},
	{"rFactor/vehicle_score/dash_indicators/mTimeBehindNext",		xplmType_Float,		0,		"",		"time behind vehicle in next higher place"},
	{"rFactor/vehicle_score/mBestLapTime",					xplmType_Float,		0,		"",			"best lap time"},
	{"rFactor/vehicle_score/mBestSector1",					xplmType_Float,		0,		"",			"best sector 1"},
	{"rFactor/vehicle_score/mBestSector2",					xplmType_Float,		0,		"",			"best sector 2 (plus sector 1)"},
	{"rFactor/vehicle_score/mControl",						xplmType_Int,		0,		"",			"who's in control: -1=nobody (shouldn't get this), 0=local player, 1=local AI, 2=remote, 3=replay (shouldn't get this)"},
	{"rFactor/vehicle_score/mCurSector1",					xplmType_Float,		0,		"",			"current sector 1 if valid"},
	{"rFactor/vehicle_score/mCurSector2",					xplmType_Float,		0,		"",			"current sector 2 (plus sector 1) if valid"},
	{"rFactor/vehicle_score/mDriverName",					xplmType_Char,		0,		"string",	"driver name"},
	{"rFactor/vehicle_score/mFinishStatus",					xplmType_Int,		0,		"",			"0=none, 1=finished, 2=dnf, 3=dq"},
	{"rFactor/vehicle_score/mInPits",						xplmType_Int,		0,		"",			"between pit entrance and pit exit (not always accurate for remote vehicles)"},
	{"rFactor/vehicle_score/mIsPlayer",						xplmType_Int,		0,		"bool",		"is this the player's vehicle"},
	{"rFactor/vehicle_score/mLapDist",						xplmType_Float,		0,		"",			"current distance around track"},
	{"rFactor/vehicle_score/mLastLapTime",					xplmType_Float,		0,		"",			"last lap time"},
	{"rFactor/vehicle_score/mLastSector1",					xplmType_Float,		0,		"",			"last sector 1"},
	{"rFactor/vehicle_score/mLastSector2",					xplmType_Float,		0,		"",			"last sector 2 (plus sector 1)"},
	{"rFactor/vehicle_score/mNumPenalties",					xplmType_Int,		0,		"",			"number of outstanding penalties"},
	{"rFactor/vehicle_score/mNumPitstops",					xplmType_Int,		0,		"",			"number of pitstops made"},
	{"rFactor/vehicle_score/mPathLateral",					xplmType_Float,		0,		"",			"lateral position with respect to *very approximate* 'center' path"},
	{"rFactor/vehicle_score/mPlace",						xplmType_Int,		0,		"",			"1-based position"},
	{"rFactor/vehicle_score/mSector",						xplmType_Int,		0,		"",			"0=sector3, 1=sector1, 2=sector2 (don't ask why)"},
	{"rFactor/vehicle_score/mTotalLaps",					xplmType_Int,		0,		"",			"laps completed"},
	{"rFactor/vehicle_score/mTrackEdge",					xplmType_Float,		0,		"",			"track edge (w.r.t. 'center' path) on same side of track as vehicle"},
	{"rFactor/vehicle_score/mVehicleClass",					xplmType_Char,		0,		"string",	"vehicle class"},
	{"rFactor/vehicle_score/mVehicleName",					xplmType_Char,		0,		"string",	"vehicle name"}
};

#endif